xcopy "..\..\st\stm32f0xx_hal_driver\*.c"  "STM32F0xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f0xx_hal_driver\*.h"  "STM32F0xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f1xx_hal_driver\*.c"  "STM32F1xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f1xx_hal_driver\*.h"  "STM32F1xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f2xx_hal_driver\*.c"  "STM32F2xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f2xx_hal_driver\*.h"  "STM32F2xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f3xx_hal_driver\*.c"  "STM32F3xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f3xx_hal_driver\*.h"  "STM32F3xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f4xx_hal_driver\*.c"  "STM32F4xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f4xx_hal_driver\*.h"  "STM32F4xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f7xx_hal_driver\*.c"  "STM32F7xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32f7xx_hal_driver\*.h"  "STM32F7xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32l0xx_hal_driver\*.c"  "STM32L0xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32l0xx_hal_driver\*.h"  "STM32L0xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32l1xx_hal_driver\*.c"  "STM32L1xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32l1xx_hal_driver\*.h"  "STM32L1xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32l4xx_hal_driver\*.c"  "STM32L4xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32l4xx_hal_driver\*.h"  "STM32L4xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32l5xx_hal_driver\*.c"  "STM32L5xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32l5xx_hal_driver\*.h"  "STM32L5xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32g0xx_hal_driver\*.c"  "STM32G0xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32g0xx_hal_driver\*.h"  "STM32G0xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32g4xx_hal_driver\*.c"  "STM32G4xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32g4xx_hal_driver\*.h"  "STM32G4xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32wbxx_hal_driver\*.c"  "STM32WBxx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32wbxx_hal_driver\*.h"  "STM32WBxx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32wlxx_hal_driver\*.c"  "STM32WLxx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32wlxx_hal_driver\*.h"  "STM32WLxx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32u5xx_hal_driver\*.c"  "STM32U5xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32u5xx_hal_driver\*.h"  "STM32U5xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32mp1xx_hal_driver\*.c" "STM32MP1xx_HAL_Driver\" /E /K /Y
xcopy "..\..\st\stm32mp1xx_hal_driver\*.h" "STM32MP1xx_HAL_Driver\" /E /K /Y
xcopy "..\..\st\stm32h7xx_hal_driver\*.c"  "STM32H7xx_HAL_Driver\"  /E /K /Y
xcopy "..\..\st\stm32h7xx_hal_driver\*.h"  "STM32H7xx_HAL_Driver\"  /E /K /Y
