name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    
    # Explicitly grant permission to create/write releases
    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository code
      # Fetch the full history to compare between tags
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generate the release
      - name: Generate and Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false